version: '3'
services:
  app:
    container_name: ts-graphql-sample
    build:
      dockerfile: Dockerfile
      context: .
    command: yarn dev
    ports: 
      - '3003:3003'
    links:
      - mongo
    depends_on: 
      - mongo
    networks:
      - local_dev_network
  mongo:
    container_name: mongo-sample
    image: mongo
    ports:
      - 27017:28017
    networks:
      - local_dev_network
networks:
  local_dev_network:
    driver: bridge
