version: '3'
services:
  app:
    container_name: ts-graphql-sample
    build: .
    ports: 
      - '3003:3003'
    links:
      - mongo
    depends_on: 
      - mongo
  mongo:
    container_name: mongo-sample
    image: mongo
    ports:
      - 28017:28017